spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localstack:4566

app:
  ses:
    endpoint: http://localstack:4566
  s3:
    endpoint: http://localstack:4566
